### ISSUE TITLE
FAQ: How to Publish the "Final" Versions of the cPP/SD

### ISSUE THREAD

**Issue by Kneckter** [itc-wgtools/cPP-Tools#102]
Q: When an iTC has completed writing a new cPP or updating an existing one, how should that iTC publish the documentation for release to the public? 

A: Once all of the work on the cPP and its Supporting Document (SD) has been accepted by the iTC and is finalized, the iTC will need to follow the versioning information provided in the [cPP Lifecycle Guide](https://github.com/itc-wgtools/iTC-docs/blob/master/cPP_Lifecycle.adoc) and refer to the procedure of publishing documents outlined in the [Document Publishing Guide](https://github.com/itc-wgtools/cPP-Tools/blob/master/IO-site/admin-guide/DocPublishing.adoc). Within the [Document Publishing Guide](https://github.com/itc-wgtools/cPP-Tools/blob/master/IO-site/admin-guide/DocPublishing.adoc), references are provided for tagging a repository with a new GitHub release number,  merging a Pull Request (to update an existing cPP) into the master branch, and creating the documentation for the final release.

**Comment by woodbe** [comment]
we should note to add the doc to the CC Portal (notify NIAP to post or have the liaison post it)
where to host the docs (site)

**Comment by woodbe** [comment]
Additional paragraphs added after what is above:

After the final documentation is created, the iTC should also have the documents posted on the Common Criteria Portal. This can be done through the scheme representative or directly by contacting NIAP (as they manage the Portal). Updates to the iTC community page on the Portal should also be provided.

Lastly, if the iTC is maintaining its own website (such as the github.io pages), the website should be updated and either directly host the files or point to their release in the GitHub repository.

**Comment by woodbe** [comment]
this is good to go

**Comment by woodbe** [comment]
https://www.ccusersforum.org/faq/doc-publication/
