### ISSUE TITLE
Comments for user guide (up to 'pull requests' section

### ISSUE THREAD

**Issue by mmbarry** [itc-wgtools/cPP-Tools#16]
Update 'is going to show  you' to 'will show you' here - https://github.com/itc-wgtools/cPP-Tools/blame/8ee2f07d8f89e4984907ec2ce78fc5d03866bc89/User%20Guidance/userguide.adoc#L38

Update 'and is required it you' to 'required if you' here - https://github.com/itc-wgtools/cPP-Tools/blame/8ee2f07d8f89e4984907ec2ce78fc5d03866bc89/User%20Guidance/userguide.adoc#L78

I suggest you leave a space between figure identifier ie figure 6 and following sentence.  I missed reading some of the following text because it got 'lost' in the figure reference.  Here is one example - https://github.com/itc-wgtools/cPP-Tools/blame/8ee2f07d8f89e4984907ec2ce78fc5d03866bc89/User%20Guidance/userguide.adoc#L124, but there are more.

Can you add something additional about how draft issues work here - https://github.com/itc-wgtools/cPP-Tools/blame/8ee2f07d8f89e4984907ec2ce78fc5d03866bc89/User%20Guidance/userguide.adoc#L223.  In creating this issue that I am writing now, there isn't really a save draft option, however, I notice that since I haven't submitted the issue yet, I just get returned to my same issue so that I can keep editing.  I did read after I did this :-) about opening another tab. 

https://github.com/itc-wgtools/cPP-Tools/blame/8ee2f07d8f89e4984907ec2ce78fc5d03866bc89/User%20Guidance/userguide.adoc#L312 - should this read 12-15 or 12-16?  I haven't totally figured out the line numbers yet in the application so I may be incorrect in suggesting 12-16

**Comment by woodbe** [comment]
@mmbarry I have fixed all but one of these in the latest version. What I'm not sure about is this one

> I suggest you leave a space between figure identifier ie figure 6 and following sentence. I missed reading some of the following text because it got 'lost' in the figure reference. Here is one example - https://github.com/itc-wgtools/cPP-Tools/blame/8ee2f07d8f89e4984907ec2ce78fc5d03866bc89/User%20Guidance/userguide.adoc#L124, but there are more.

I saw spaces between them, but I don't know if that got taken care of later or if you are actually referencing places where I actually had a graphic embedded directly into the text (there were places where I just put an image of the button you would press instead of saying it, so like "Comment" could instead be an image of the "Comment" button).

**Comment by mmbarry** [comment]
Looks good Brian - thanks!
