### ISSUE TITLE
Comment for admin guide

### ISSUE THREAD

**Issue by The-Fiona** [itc-wgtools/cPP-Tools#19]
We should recommend that least one of the team need to replicate (backup) the repo locally...

This is best practice with any cloud service: Here's one example of why:
https://www.theregister.co.uk/2019/06/07/github_repos_wiped_without_notice_quickly_restored_but_why/

**Comment by woodbe** [comment]
I would agree, though a quick search doesn't reveal an "easy" answer that doesn't cost money or require someone to really be a developer. Definitely something to have though.

**Comment by atsecsysad** [comment]
Option 1: 

https://github.com/awaescher/RepoZ .. This might be a solution to that problem although it depends on the goal here. Option was found here: 

https://stackoverflow.com/questions/53997647/git-client-software-to-pull-several-remote-repositories-at-once

The feature I'm most intrigued by is the auto-fetch function that can automatically pull new updates from repositories. That's certainly easy for the users. 

Option 2: Reading up on git, the clone command with mirror will work just fine: 

git clone --mirror https://github.com/itc-wgtools/cPP-Tools ./cPP-Tools-Test/

This version is a true backup of the raw repository by the way. To extract the repository data that we care about: 

git clone ./cPP-Tools ./cPP-Tools-RealData

As normal.

**Comment by woodbe** [comment]
My biggest concern would actually be not the repository directly but the Issues. Pull requests are all marked with branches which can be available for anyone with a GitHub client, but I don't know what happens to the Issues and the commenting around the PRs in these cases. So while you would have your work, which is important, you may lose the context and history surrounding decisions and such in the project.

**Comment by atsecsysad** [comment]
**Option 1**

Looks like the account owner for GitHub can do this manually: 
https://help.github.com/en/articles/requesting-an-archive-of-your-personal-accounts-data

**Option 2**

Or it can be automated: 
https://github.com/josegonzalez/python-github-backup

Tested Option 2 with my own repository by doing the following:

1. Installed python package using the install instructions in the front page (sudo su && pip install github-backup)
2. Went into GitHub -> Settings -> Developer Settings -> Personal access Tokens. Created an access token so password wasn't required. Set decent ACL's for the access token, though did not include access to GPG keys, etc.
3. Used the following CLI:
  `export ACCESS_TOKEN=<accessToken> &&
  github-backup username -P -t $ACCESS_TOKEN -o ./github-backup_DL --all -O -R repository`

**Result**

- Folder automatically created.
- Sub-folders: account and repositories created automatically
  - account folder contained followers/following, starred, and watched json files.
  - repositories folder contained hooks, issues, labels, milestones, pulls, and repository sub-folders. 

I previously generated an issue, and commented on it, just to see if it was possible to download them. It worked fine. 

The repository sub-folder appears to be a cloned copy of the repository as well. This is not a raw form of the repository however, so I would say this would be better served in conjunction with the other clone/mirror function as mentioned earlier in the discussion.

**Comment by woodbe** [comment]
Probably can be closed based on the current admin guide draft.

**Comment by woodbe** [comment]
Closing this based on current admin guide draft which has all this content.
