### ISSUE TITLE
Consistent example iTC?

### ISSUE THREAD

**Issue by woodbe** [itc-wgtools/cPP-Tools#22]
So looking at the CC Portal Page template and then the Status Table template we have difference examples for the iTC name. In the Portal Page we have "Your" as the iTC name and in the Status Table we have "Coffee Maker". 

Now I actually like the idea of having Coffee Maker as the default (Microsoft always had one I can't remember anymore they used for everything from documentation examples to training, and at a few companies since I have done the same thing to make things look more consistent).

So I'm good with Coffee Maker, but I think we should then standardize on it and use it everywhere for names and such. The biggest advantage I can see is that we can end up with a few well-defined terms that anyone can more easily see as "wrong" in their finished document because they are from the examples.

So to that end, what does everyone think about these:

Long name: Coffee Maker iTC
Short name: CM-iTC
URL (for work): https://github.com/coffeemaker/
email address: cm-itc-mailing-list@gmail.com
Chair: Johann Sebastian Bach
Project Manager: Ludwig Van Beethoven
DATES: Use <DATE> (use the brackets so it stands out)

One question about the URL is whether it should be something like https://coffeemaker.github.io instead? Maybe have the iTC create a page there that points to the various repositories (and provide a basic template?).

**Comment by ansukert** [comment]
If I understand what this is asking, we would create the templates around a standard "Coffee Maker" iTC. Subject to what happens to my suggestion in Issue #23 and, if so, when it happens I think standardization like this is good and I support it.

**Comment by woodbe** [comment]
@ansukert @The-Fiona 

Do you think we can treat this Issue and #23 as iterations? Basically I would go back through and finish filling out the fields here (I have already started using them for an example using a variable for the iTC names) and then work on the larger one later?

**Comment by The-Fiona** [comment]
I am fine with that. I was trying out the "coffee maker" idea , I am happy that we at least consider it. I think it makes the document less "dry". Yes, the coffee maker has been used before, there is still a stub on the CC-Portal for one. I had no idea that it originally hailed from MS. I hope they do not claim IP rights LOL.

**Comment by woodbe** [comment]
This is the one I remembered:
https://en.wikipedia.org/wiki/Contoso

Apparently they have used a lot of fictional companies over the years (including Fourth Coffee), but it helps standardize the expectations and unify the examples. 

I have created a wiki page [here](https://github.com/itc-wgtools/cPP-Tools/wiki/Dummy-iTC-for-Examples) to keep track of what should be used.
