### ISSUE TITLE
Review of ToR Template

### ISSUE THREAD

**Issue by ansukert** [itc-wgtools/cPP-Tools#36]
Brian, 

I will approve this but before I do it I have some comments, including one major one, as follows:

1. While we were having the discussion of Voting procedures in the template I looked at the voting procedures that we have for the Printer Working Group that I am the Xerox rep for. They are very similar, although the PWG's are much more formal than we would probably want for an iTC. However, there is one thing the PWG process did have that might help address one of your questions we discussed this morning. 
Right now in the template you have as follows --

**Comment by woodbe** [comment]
@ansukert It looks like you accidentally hit comment before finishing

**Comment by ansukert** [comment]
Brian,

I know. I just submitted my full comments. They are against the older version but they should apply to the newer version also.

Al

**Comment by woodbe** [comment]
Closing for #37
