### ISSUE TITLE
Review of ToR Template

### ISSUE THREAD

**Issue by ansukert** [itc-wgtools/cPP-Tools#37]
Brian,

I will approve this but I have a few comments, including one major one, that I wanted you to discuss first.

1. While we were discussing Voting at the WG Meeting this morning I looked up the Voting rules for the Printer Working Group (PWG) which I am the Vice-Chair of. Turns out the voting rules are similar, although the PWGs are more formal that I think is needed for an iTC. But there was one thing the PWG included that might help address one of your questions we discussed this morning. Under Voting you indicate the following--
Negative votes are accompanied by a technical reasons

The PWG expands that to say:
Negative votes are accompanied by a technical reasons and a description of the changes that would be required in the document to turn a NO vote to a YES. 

I think that addition would help address the problem you are concerned about here. 

2. The PWG voting process has a quorum requirement - 25% of the eligible members (where in the PWG case members are companies). I wonder if some type of quorum requirement is needed for iTC voting also (although I will say we didn't include one in the HCD TC ToR we submitted to the CCDB).

3. We included the following statement in the HCD TC ToR that I think should also be included in the template -- It is the responsibility of each organization to determine which individual member will cast a vote on its behalf. 
Might help address another one of your questions we discussed this morning.

4. Given the comment that Fiona made at the meeting this morning, maybe something should be put in the template at the beginning that iTCs are free to change the Voting procedures as they deem necessary.

5. This is mymajor comment. I will preface this by saying this was a major issue that we "discussed" at the HCD TC when we developed our draft ToR to be submitted to the CCDB.

Under Technical Decisions, you have as follows --
. An issue is posted by a member, preferably including the member’s proposed solution
. The Core SMEs considers the issue and comments
. The Core SMEs post a proposed resolution
. Technical Editor and original issuer reviews the proposed resolution
. Technical Editor makes a judgment
.. Needs further study – notify the {iTC-shortname}, send back to (3)
.. Needs a vote – iTC votes, then send back to (5)
.. Proposed resolution is accepted – notify the {iTC-shortname}, implement, and close issue
. Implement 5(c) and close the issue.

Our initial ToR had the same wording and many of us on the HCD TC (myself included) did not like it at all. Our major problem was the statements "Technical Editor and original issuer reviews the proposed resolution" and "Technical Editor makes a judgment" -- the Technical Editor should not be making any decisions on what to include or not include in an iTC document; that decision should be made by the iTC Chair or that person's delegate. I agree that once the decision is made the editor can determine how to implement it, 

I really think you need to rethink the Technical Decision process. I should note that the HCD TC took that section from one of the other ToRs (I forget which one) as something to reconsider:

Decisions will be made by a consensus of the participating members. Consensus is defined as receiving no documented objections during the decision period.
Decisions may be made via email or during an in-person meeting or telephone conference call.  In the case of email, the iTC will provide one or two weeks to make the decision.  For in person or telephone conference calls, only members that attend the meeting will be able to participate in making the decision.
Consensus is the default and strongly preferred method for resolution.  However, if after a month consensus cannot be reached for a particular issue, then majority voting will be implemented.  
If there are members that disagree with a decision, they can request the reason for the objection to be documented.
Once a decision has been made by the group it will be adopted and implemented.  However, as a means to change direction or scope, any member can try to build a consensus for reversing a prior decision.
Only the iTC can decide to change the Terms of Reference for the Community.

**Comment by woodbe** [comment]
@ansukert Thanks, this is good. Here are my comments back to be clear (and I'm happy to make the updates before you approve, I can do it tomorrow morning).

2. I don't have an issue adding a third category of a "conditional yes" where you have to make some changes. It obviously adds some complexity, but is fine, it is basically a more explicit version of what we were talking about. I'm good with making the recommendations we have as clear, concise and easy to follow as possible.

3. I did add some additional text around the multiple votes, see if you think this works

https://github.com/itc-wgtools/cPP-Tools/blame/13cf71536bad7845b59844b3062c1f609d028304/Templates/iTC-ToR.adoc#L198

4. I did add this to the beginhning (after the consensus definition)

https://github.com/itc-wgtools/cPP-Tools/blame/13cf71536bad7845b59844b3062c1f609d028304/Templates/iTC-ToR.adoc#L146

5. Are you suggesting taking that text and replacing the current Technical Decision section, or just using that as a reference? I actually agree that the ToR section is not really that good and actually probably is a place where setting multiple voting procedures is good, but I just want to be clear what you are suggesting right now. I'm Ok moving forward with what you propose immediately and letting it out for further review that way.

**Comment by ansukert** [comment]
Brain,

I’ll look at the other changes, but for #5 I am suggesting that what we had in the HCD iTC ToR that I put in the comment or something similar replace what is there now under ‘Technical Decisions’.

Alan

**Comment by woodbe** [comment]
@ansukert I have made the update to the technical decision section. I didn't quite take the whole thing, but I got what I think is needed there (I made a few edits before that part as well, so I think it has what you are looking for).

**Comment by ansukert** [comment]
Brian - I think you can close this Issue now with the updated ToR template I just approved.
