### ISSUE TITLE
New "admonition" block for templates

### ISSUE THREAD

**Issue by woodbe** [itc-wgtools/cPP-Tools#38]
I was thinking about this while making an update and found there is a way to create customer admonition blocks. These are the "NOTE", "IMPORTANT" and such that have been placed into the docs. 

My thinking is that I create a custom one (or more) (using the built-in capabilities of Asciidoctor extensions) and that we can then use to explicitly mark text for different things.

For example, one could be used explicitly for explaining something. A second could be to mark boilerplate (or the opposite, the things that can be changed, or both). 

My thinking is that with custom admonitions we could more easily tell someone to get rid of them in their templates because they wouldn't be the "normal" admonitions.

Thoughts?

**Comment by woodbe** [comment]
I have been working on this, adding custom admonition blocks (I have it half done, I can create them for HTML output, but I'm asking for help on the PDF side as that has be stumped). 

This leads me to a question though, about what admonitions we would like to have here. Based on the comments so far, I see these as being useful, but I would like comments/feedback on whether more should be added. Remember that the point of these is that they would be explicitly used for the purposes of pointing things out to the users of the templates, and so are things that should be easy to find and remove when publishing the document. This is why I don't want to use the ones that are default like NOTE and IMPORTANT. I want something that would stand out separately, so when you build your output and see these, you KNOW that you have to take them out.

- BOILERPLATE - this is for sections that must be this way (based on convention, etc). I don't know if this would be used often, but would be there to be clear
- REVIEW - this would be used to mark sections where the text may be "complete" but should be reviewed and edited for the iTC
- GUIDANCE - this would be used specifically to mark text that may provide an explanation about the section

One of the big questions about these is the user of BOILERPLATE vs REVIEW. Basically these are opposite, and probably shouldn't both be used at once. My thinking is that REVIEW may actually be a better normal use one, so if you see a REVIEW note, then you know to edit this, but if you don't, then you know you should probably leave it? My thinking is that to some extent you use one and the other one is implied. 

Thoughts?

**Comment by ansukert** [comment]
Brian,

I like the idea a lot - it fits with several of my comments about telling the user what to change and what to leave alone. 

As I sometimes tell my wife, I think you may be overthinking it here. The three types of admonitions you have - BOILERPLATE, REVIEW and GUIDANCE are just fine. You might tweak the definitions a little (see my suggestions below), but leave the three types of admonitions as you have them. 

- BOILERPLATE - this is for text that should be inserted into the document exactly as worded in the template (based on convention, etc). 

- REVIEW - this is for text that should be reviewed and edited as needed for the iTC in question

- GUIDANCE - this is for text that provides guidance on what should be included in that particular section

**Comment by davidthesis** [comment]
I see the point that Boilerplate and Review are opposites and was leaning towards only having one but I think with Alan's definitions it is probably OK to have both - I am assuming that any text that has neither would generally be OK to change if necessary (but unlikely to need it). I have also been considering admonitions as I am looking at the iTC white paper in (rare!) spare moments. That has some marked sections in the word doc/pdf for things like initial uses only (things that we are likely to want to get rid of anyway in the new draft) - so I have just been using titled sidebars but admonitions would be nicer. It would need diving into the doc book xsl to do custom ones for pdf though - I may get to look at that sometime but not yet!

**Comment by davidthesis** [comment]
That was David M with a different github account (I forgot I had been using that one last)

**Comment by woodbe** [comment]
@researchcollab @davidthesis (so you get it either way)

Thanks, that does make sense. I have opened a question on the Asciidoctor forums (someone else was asking something similar some time ago but the answer wasn't clear), so I hope to have something that will work. I have uploaded the extension code necessary to do it for HTML, it just needs to be added into the proper folder in the program and called and seems to work fine in testing.

**Comment by davidthesis** [comment]
many years ago (when we were trialling a new approach that was to be CC version 4) I actually had Bob Stayton of Sagehill on contract because we were using Docbook heavily and wanted customisations - shame that contract was so long ago :(

**Comment by woodbe** [comment]
Ok, I have successfully created these three admonition blocks, they just need to be used in the templates now.

**Comment by woodbe** [comment]
I am adding some new blocks for @davidthesis and will also create a basic guide for doing so in the future (a wiki page here, since this is not something I expect to need to be done on an iTC basis).

**Comment by woodbe** [comment]
(Some links for my reference when I create the short guide)

https://fontawesome.com/v4.7.0/

https://fontawesome.com/icons?d=gallery

**Comment by woodbe** [comment]
I have placed a document describing how to create admonitions here:

https://github.com/itc-wgtools/itc_gentools/blob/master/Creating_Admonitions.adoc

**Comment by woodbe** [comment]
Closed based on verbal agreement on 9/11/19
