### ISSUE TITLE
SFR examples page

### ISSUE THREAD

**Issue by woodbe** [itc-wgtools/cPP-Tools#39]
Check out this [page](https://itc-wgtools.github.io/PP-examples.html). This has an example pulled from the Biometrics cPP and includes the SD for it as well.

I would add a TOC to this in the future to make finding things a little easier, but I posted this using the extended component definition and not just the short requirement itself, so it has more information, but may be more difficult to follow.

This is in related to #31, #32 comments to have examples, but not to place them inside the templates themselves.

**Comment by ansukert** [comment]
Brian - I like it; it is clear and understandable. Might have picked an example that was a little shorter but that's nit-picking. 
As a side comment, I have never understood what Component Leveling is or why it is needed in an Extended requirement definition. Maybe in an update you could explain what it is, but for now this is good.

**Comment by mmbarry** [comment]
Hi Brian, 
Looks good.  I just noticed you refer to Assurance Activities in a couple of places instead of Evaluation Activities.  You do use EA correctly in most places.  When you replace Assurance Activities with Evaluation Activities - you probably want to define EA.

**Comment by woodbe** [comment]
@mmbarry Funny you should say that, I literally copied that entire section out of the Biometric PP-Module without any edits (so it looks like I need to make some edits to that document).

@ansukert Component Leveling is needed to basically match up with CC Part 2. So if you have a requirement, it needs to be defined. All non-EXT requirements are already defined there, but any you create yourself need to be explicitly defined so they are clear for anyone else. I copied that part because while it is more than is needed simply for the SFR itself, it has everything an SFR created by an iTC would need to complete the cPP.

**Comment by woodbe** [comment]
Unless anyone has further comments on the templates as I have updated them in the new site, I will close this issue.
