### ISSUE TITLE
Advanced User Guide

### ISSUE THREAD

**Issue by ansukert** [itc-wgtools/cPP-Tools#48]
Brian,

Let me say at the start that this Advanced User Guide is really well done and understandable; I could even follow it. My comments are mostly grammatical type things with one exception. 
1. The following links do not appear to work in the draft I reviewed:
Section 1 - [Asciidoctor Editors] 
Section 2 - [GitHub Clients Overview]
Section 3.3.2 -  here.
Section 4 - [Asciidoctor Editors with Live Preview]
Section 4.1 - [AsciiDocFX].   

2. Section 3.2 - in the sentence "Accessing a repository will make it available to download to your computer. When you installed the client it would have asked you to specify a GitHub folder, and this will be where the files are downloaded (be default)" I think it should be "by default".

3. This is my only "technical" comment. I had a hard time following the discussion in 3.3.2 on switching between branches. I am not sure if there is anything that you can do, but maybe an Informational sample/discussion like you have done elsewhere in the document might help. Look it over and see what you can do to clarify this topic.

4. Section 3.3.3 - in the sentence "Files will be marked with symbols for new, modified or deleted files (greed, yellow and red)" I am assuming that new is marked green (not 'greed'), modified is marked yellow and deleted is marked red. To clarify that I would suggest this - "Files will be marked with symbols for new, modified or deleted files (green, yellow and red, respectively).

5. Section 3.3.3 -- " (this can be right with a right-clicki)" I think should be " (this can be done with a right-click)"

6. Section 3.3.3 -- "You can use the @ and # references for people " - I am not sure what the @ and # symbols mean; is that something you would expect someone using this advanced guide to know at this point? If so OK, although a pointer to where they are defined wouldn't hurt here.

7. Section 4 -- "Once you have the files for the repository downloaded locally, you need to something to edit them with" should be "Once you have the files for the repository downloaded locally, you need to find (or have?) something to edit them with"

8. Section 4.1 -- "Special admonitions will not be display properly" should be "Special admonitions will not be displayed properly"

**Comment by woodbe** [comment]
@ansukert I think the problem you had in 3.3.2 is solved by fixing the link (the URL had been copied twice into one long string that obviously didn't work). I added the basic user guide as a resource as well.
