### ISSUE TITLE
iTC User Guidance for GitHub

### ISSUE THREAD

**Issue by ansukert** [itc-wgtools/cPP-Tools#49]
Brian,

This another very well done document that is also understandable. But I do have some comments:
1. Need to add the appropriate references in the References section

2. Section 1.1 - Will the "Asciidoctor for iTC Syntax Reference" eventually be a pointer to this template document.

3. Section 1.2 - I am not sure if this is a comment to you or a comment to myself. It states that "An Issue can be created that is tied to a specific point in a document " - in what document will I find instructions on how to do that.

4. Section 1.2 - "At some point the "Master" is published and this will create say v1.0 of you document " should be "At some point the "Master" is published and this will create say v1.0 of your document"

5. Section 2.1 - Figure 1 did not come out properly (I am assuming here the purpose of the figure was to show the user how to sign up to GitHub).

6. Section 2.2 -- It states that "There are four primary areas within GitHub " but Figure 2 shows five areas. There is no subsection in 2.2 for Projects.

7. Section 2.2.1 - "switching to the Master branch would not show that image while the devlop branch will.." should be "switching to the Master branch would not show that image while the develop branch will..."

8. Section 2.2.3 -- the  [Using Pull requests]. link does not work.

9. Section 3.1 - Will the Asciidoctor for iTC Syntax Reference eventually be a pointer to this document?

10. Section 4.1 - the two figures in this section did not come out properly. Same comment for Section 4.2, Section 5.1, the last two figures in Section 5.4, the figure between Figure 27 and Figure 28. the last Figure in Section 5.5, first sentence of Figure 5.6.1, last sentence in Section 5.6.2. 

11. Section 4.2,1 -- "When creating (or reviewing) and Issue (or Pull request)," should be "When creating (or reviewing) an Issue (or Pull request),"

12. What I think is missing (and this is what I really need) is how to create a PDF version of a document that is either in a Pull request or has been approved.  I need to get a PDF of this document so I can start using it and see if there are steps missing.

12.

**Comment by woodbe** [comment]
@ansukert I have made corrections to these.

I could not see problems with the images as you were, so I'm not sure what the problem is there.
