### ISSUE TITLE
Table of Contents location

### ISSUE THREAD

**Issue by woodbe** [itc-wgtools/cPP-Tools#5]
Looking at the existing templates and docs currently in use the standard seems to be to have the table of contents appear after several pages. I'm familiar with putting a boilerplate page after the title page (things like copyright and versioning) though that doesn't exactly seem to be what is going on in the existing docs.

The template I have produced so far has the TOC immediately after the title page.

So the question is, should the TOC be moved later in the document (which can be done easily), or left as the first thing?

**Comment by The-Fiona** [comment]
Both CC and Iso have it fairly early on in the document. It is not numbered.

**Comment by woodbe** [comment]
OK, looking at the CC itself, there is a forward and a legal notice before the TOC. I would consider these to largely be "boilerplate" stuff, and will adjust the templates to place this type of content before the TOC.

**Comment by woodbe** [comment]
@The-Fiona please review the latest develop branch documents and see if this works. I have moved the TOC around in all of them and tried to make the different docs a little more consistent. That doesn't seem to have been a thought in the previous documents, even in the templates, so it is a little messy with some having different content up front.

I'm ready to close this if the latest updates to the template as satisfactory.

**Comment by woodbe** [comment]
Closing
