### ISSUE TITLE
cPP Template Comments

### ISSUE THREAD

**Issue by ansukert** [itc-wgtools/cPP-Tools#51]
I'll figure out how to integrate the comments with the actual document, but for now it is the "old fashioned" way.

Couple of minor things on the cPP template for next update:
1. The guidance in Section 5.1 is somewhat contradictory. You say "The following sections have been included from CC Part 2 just as reference. Each section will have to be filled out. If the class isn’t needed it can be removed." - you are saying each section has to be filled out but if a class isn't needed it can be removed. Since each class is a separate section this can cause confusion if, for example, there are no FPR requirements. I know and agree with you are trying to say; maybe we can say it clearer so there  is no confusion, say something like "Include only those classes in 5.2 - 5.12 for which the TOE will need to comply with one or more SFRs from that class" (only more concise).

2. Many cPPs like NDcPP include an appendix for the Key Management Description (KMD)requirements in the cPP. I think you should add that one just like you did for Entropy because the two (entropy and KMD) typically go together.

3. The following links do not work properly:
- all the SD links
- https://coffeemaker.github.io/PP-config.html in 2.1
- Selection-Based Requirements. in Appendix B

4. I think the sample extended component definition is really good; I think you include a statement (if it is true) that all of the sections shown in the example are required (because I think they are). You known what I am going to say next - I think you also need a sample (either in the template or via pointer to some other location) of a use case (they are not as easy to do as you think), the Security Problem Definition (all 3 sections), the Security Objective (all three sections) and maybe an SFR definition just to show the format.

Overall this template is really good and will help a lot.

**Comment by woodbe** [comment]
Closing based on latest updates
