### ISSUE TITLE
Should we have a specific SPD template?

### ISSUE THREAD

**Issue by woodbe** [itc-wgtools/cPP-Tools#55]
I was thinking about the stages for the iTC, and one of the early ones is to create the SPD. While this is obviously part of the ST, I'm wondering if we should create a basic template with those sections pulled out just so it is easier to work on from that point.

In terms of where this would go (in terms of admin vs cPP repository), I'm thinking this is actually when the cPP work really starts, so it would be a template with the cPP/SD/PPC.

Thoughts? This will be quick to create, but I want to know what everyone thinks.

**Comment by mmbarry** [comment]
Good idea!  I think we should have a template for it...especially since it gets posted for public comment.  It is similar to the ESR which we have a template for.  I agree Brian...it goes with the cPP repository.

**Comment by ansukert** [comment]
I agree with Maureen. Anything we can do to make an ST author's like easier is going to be a big help in the long run, and templates are a great way to do that. Go for it!

**Comment by woodbe** [comment]
OK, I will create a short template for this today and add it to the repository.

**Comment by woodbe** [comment]
Closed based on verbal agreement on 9/11/19
