### ISSUE TITLE
Section numbering

### ISSUE THREAD

**Issue by woodbe** [itc-wgtools/cPP-Tools#6]
I was just realizing looking through the cPP and SD I have for the biometrics that the cPP numbers all sections while the SD has a "Foreward" section that isn't numbered.

I think these should be consistent since it seems strange to have different documents following different numbering standards (if I look at the NDcPP docs I find some sections not numbered and then starting a "0" in the PP while fewer sections are not numbered in the SD). 

I'm fine with intro type stuff being unnumbered, but I think that should be used in all the docs, not differently for each one.

Thoughts?

**Comment by The-Fiona** [comment]
I agree.
In both ISO & the CC the foreword is not numbered. So I agree to be consistent, and in this case would suggest not numbering it to match the higher-level docs...

**Comment by atsecsysad** [comment]
I spent a bit of time researching the "more appropriate" way of doing this from a tech writing standpoint, and the overall conclusion was that Preface and Foreward are not included in the main numbering scheme, (i.e., Arabic page numbering), whereas the Introduction is the first page in said numbering. The Preface/Foreward have their own numbering (i.e., lowercase roman numerals) scheme usually, but I'm not convinced asciidoc supports that out of the box. 

The question then becomes how do we massage asciidoc into having two types of numbering, while both are included in the TOC ?

**Comment by woodbe** [comment]
https://github.com/asciidoctor/asciidoctor/issues/979

The last item in this issue may solve this (to some extent). I haven't checked into it to see how it numbers or not. The "simple" solution is to just leave those pre-sections as not numbered.

**Comment by woodbe** [comment]
Here is the response from the lead developer. I think this is a future, and for now we leave it as un-numbered.

This is not something that is supported out of the box. You can do it, but you need to manipulate the parsed document yourself. You can do so using a TreeProcessor.

What you are looking for is the `numeral` property on the section nodes. This property accepts a string, so you can set it to whatever you  want.

Here's an example:

Asciidoctor::Extensions.register do
  tree_processor do
    process do |doc|
      sections = doc.sections
      sections[0].numeral = 'i'
      sections[1].numeral = 'ii'
      (sections.slice 2, sections.length).each do |sect|
        sect.numeral = sect.numeral.to_i - 2
      end
      nil
    end
  end
end

You can find a similar type of extension in the lab: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/sectnumoffset-treeprocessor.rb

**Comment by woodbe** [comment]
I'm going to close this. I have marked it on the [wiki](https://github.com/itc-wgtools/cPP-Tools/wiki/Future-Investigations) as something for a future investigation.
