### ISSUE TITLE
project boards and maintenance

### ISSUE THREAD

**Issue by woodbe** [itc-wgtools/cPP-Tools#60]
The ND iTC has a nice document about how they perform maintenance, and I have been looking at how to automate this in GitHub to some extent using Projects. The problem is that what I can find is very manual, which is probably OK to start, but somewhat limited I would think.

I found this [project](https://github.com/philschatz/project-bot) that could form the basis for what we would want, but it currently doesn't support the types of things I think are needed. Using this you can automatically move items to different columns within the project, but what I want to be able to do is assign different labels and use this to calculate "priority" levels based on the types that are covered (ideally the bot would actually calculate the values and do this, but I could like with some manual work here).

The thinking is that for new requests, a project called maintenance would be created. Anything that comes in as an "enhancement" would be added to this project (though it looks like this would have to be done manually, at least this is a step that isn't too bad).

From there what I was looking at was to create different labels that would account for the prioritization as laid out in the maintenance doc from the ND. Then based on the number of labels added (with their associated point value), they would be moved into separate columns, showing some level of the prioritization of the enhancement requests. As they get approved to be worked on they would be moved to a different project. 

The main thing I was trying to get to was an automated way to have the prioritization calculated for the board. They can be manually ordered around, so this can be done manually without any tools, which may just be the thing to do.

**Comment by woodbe** [comment]
So here is what I'm thinking at this point (general flow):

1. Request comes in and is automatically assigned the "enhancement" label along with the cPP/SD/PP-Config from the issue template
2. The issue is assigned to the Maintenance project
  a. I was thinking to add a request to add to the proper project as part of the Issue template, but it can be done manually anyway later
  b. Here the project would be automatically assigned to an "Incoming" or "To do" column
3. The admins would do a little triage on the new issue and if appropriate, add the "Awaiting Priority" label which would let everyone know that it is ready to be looked at generally
4. The iTC would assign priority labels to the issue (from the different labels)

This column would be manually sorted (i.e. the admins could order it based on the number of labels and their values, as there isn't any way to do this automatically at this time).

5. Once issues had agreed priority, they would be labeled "Awaiting Review" to mark they are ready to be worked on
6. Once the issue is being worked on, it would be marked "In Progress"
7. At this point the expectation is that a Pull Request would be created, and once the PR has been approved, the Issue would be closed.

So the adding of the labels would allow the Issues to be moved between columns in the project automatically, helping provide a little automation within the Maintenance Project.

Thoughts?

**Comment by woodbe** [comment]
I have been looking more closely at the maintenance vs the IT process, and what I see is basically the same. As I see it, the differences between them are:

- Target
  - IT are requests based on the current public version, and need immediate decisions
  - Maintenance is for the "next version"
- Timeframe
  - IT is "urgent" as it is for things that are ongoing (or soon planned) based on the current public versions
  - Maintenance is more of a "as we get to it" with a goal for some release timeline, but not a specific target or urgency (at least up until you get close to the release date)
- Voting
  - Acceptance of a decision MAY need special voting given that it is an out of cycle update

So what I'm thinking is to create two separate projects specifically for general maintenance (largely the incoming enhancement requests) and IT. The iTC could create additional projects based on this for other topics, or fold general updates into the maintenance.

I have created example projects here:
https://github.com/itc-wgtools/Admin-testing/projects

If you create a dummy issue with the label enhancement and assign it to the project, you can then track its progress through as you change the label.

Also, I think the IT intake form can just be another Issue template, so we should be able to use the same setup to handle these incoming requests.

**Comment by ansukert** [comment]
Brian,

Agree in principle with what you are saying.

I am not sure I understand what you are saying about Voting however. The voting processes between an Interpretation Team and a Maintenance Team would probably be slightly different because of the differences in urgency you point out. For example, I could see an IT allowing for some type of “emergency” off-line email type of voting process for a real emergency issue if a conference call could not be arranged in a timely manner (I don’t know if the NIT ever did anything like that) whereas an MT would probably always do their voting through a F2F or Conference Call meeting. I guess that is what you were trying to say below.

However, I have a general question about voting in that there is always this pull between trying to achieve consensus and what to do if you can’t achieve consensus. I still am not sure we are handling this properly but I am not sure there is a proper way of handling it. I think each iTC should be allowed to determine whether they want to go the democratic route or the autocratic route in such a situation and not force one particular method on the iTCs and our templates should allow for that. I am assuming they do – just wanted to point that out.

Alan

**Comment by woodbe** [comment]
@ansukert so in general, I expect voting will actually be handled by approvals to pull requests. To accept changes, some determined number of people must approve the change, and that basically counts as the vote.

What I'm not as sure about though is handling the voting for an IT specifically on a technical decision. Generally the IT is a subset of the whole iTC membership, and as I get the NIT docs (which someone else should chime in to make sure I'm correct), the NIT makes the decision on the TD without having full approval by the iTC, so the NIT can make a change to the PP/SD. So basically this is a little different than the whole iTC voting on something, and as such, the IT process should have a well-defined set of parameters (this could mean voting in the same way, but solely by the membership of the IT, but it should be defined).

So going back to the original ToR discussion, my general point about voting is that it should be well defined what the expectations are. Saying we will do everything by consensus is great, until the moment you don't have it, and at that point you need to know what the next steps should be. For something like the IT, the group needs to work quickly (it appears the expectation for the NIT is about 2 weeks turn around or less, which seems reasonable given the nature of the types of requests). 

I guess what I'm really saying here is that there may need to be something different for voting here, specifically for the IT, but likely it could handled in GitHub in the same way. It may require a new branch, or even a new repository?

**Comment by ansukert** [comment]
Brian,

You’ve thought it out well and it all makes sense.

Alan
