### ISSUE TITLE
FAQ: Scheduling meetings

### ISSUE THREAD

**Issue by mmbarry** [itc-wgtools/cPP-Tools#88]
Meeting regularly is an important part of iTC collaboration.  Even during slower work periods, it is recommended that you maintain a regular call schedule to keep members engaged and to hold the timeslot.   At a minimum, monthly cadences are recommended.
Check with your active members to confirm meeting attendance since there is no need to accommodate someone who will not be regularly attending meetings. 
Choosing the regular time slot schedule can be challenging when balancing multiple time zones.  This time zone converter website - https://www.timeanddate.com/worldclock/converter.html - may help you choose some appropriate times to meet.   Once you determine 4-5 good meeting times, survey the group for the best choice using:
- simple email
- doodle poll - https://doodle.com/free-poll
- limesurvey - link?

**Comment by woodbe** [comment]
https://www.ccusersforum.org/faq/scheduling-itc-meetings/
