### ISSUE TITLE
FAQ: What is the best way to have review comments submitted to the iTC? 

### ISSUE THREAD

**Issue by ansukert** [itc-wgtools/cPP-Tools#90]
Since GitHub is starting to be used more extensively by new iTCs for creating cPPs and SDs to take advantage of the templates created by the CCUF Tools Working Group, the use of the GitHub Issues Template is a very good way of submitting review comments to the iTC. You can find the information on how to use the GitHub Issues Template in Section 2.2.4 of the iTC Administrator Tools Overview at iTC Administrator Tools Overview (itc-wgtools.github.io). 

Another way of submitting comments to the iTC is via a spreadsheet. A good sample spreadsheet to use is the Comments-Matrix-Template.xlsx comment spreadsheet template developed by the CCUF Tools Working Group that you can download from itc-wgtools/iTC-docs: A repository for the creation of templates for creating and managing an iTC. (github.com). 

Lastly, comments can always be submitted to the iTC via email. 

Whatever method is used, make sure the comments contain as a minimum the following information:
•	What document the comment is against
•	Location in the document the comment is against
•	What the comment is
•	If the comment is denoted an error or something that requires a correction, the suggested correction action

**Comment by woodbe** [comment]
If using email for comments, specify where it should be sent. Either the main mailing list (not ideal), or to a list of people, or if possible, have a separate editor email list setup and use that.

**Comment by woodbe** [comment]
https://www.ccusersforum.org/faq/what-is-the-best-way-to-have-review-comments-submitted-to-the-itc/
