### ISSUE TITLE
FAQ: Meeting Agenda 

### ISSUE THREAD

**Issue by ansukert** [itc-wgtools/cPP-Tools#91]
Meeting agendas should be generated and distributed to potential meeting attendees at least two days before the scheduled meeting date if at all possible. There are instances where that cannot be avoided, but that should be the general rule to follow. You can use whatever word processing tool you are familiar with to generate the agenda.

Meeting agendas should include the following information:
•	The meeting that is to be held (in this context a conference call is treated as a meeting)
•	The date and time of the meeting
•	If it is a virtual meeting, the link to the app (e.g., Zoom, WebEx,) location, meeting information (password, meeting ID, etc.) and dial-in information necessary to join the meeting
•	If it is an in-person meeting, the location of the meeting
•	The agenda for the meeting usually in bulleted form

You should also include in the meeting agenda any other information meeting attendees might need to know before the meeting such as links to documents/information or other meeting pre-reads. When you are done with the agenda and done the necessary review and spell-checking, you should generate a PDF version of the agenda; that should be the version you should send out and store. 

As far as sending out the meeting agenda, it is easier if you have a pre-defined DL to send the meeting agendas to, especially if there are a large number of members in the iTC. Otherwise, keep a list of email addresses you need to send the meeting agenda to. 

The actual email itself should include the meeting agenda with the information listed above – pre-reads will likely be either attachments to the email or links included within the email. The subject of the email should be something like “<Date> ABC iTC Meeting Agenda” or some variation of that. What order you put the information in the body of the email is up to the preparer, but typically the body of the email starts with, in order:
•	the meeting that will be held
•	the date and time of the meeting
•	the location of the meeting (if it is an in-person meeting)
•	the agenda of the meeting
•	description of any additional information and pre-reads including links
•	if a virtual meeting, all the information needed for someone to join the meeting

Not all iTCs store meeting agendas, but if you do store meeting agendas they should be stored in the same location as meeting minutes are stored (see the FAQ for Meeting Minutes).

**Comment by woodbe** [comment]
https://www.ccusersforum.org/faq/do-i-need-a-meeting-agenda-for-my-itc-meetings/

https://www.ccusersforum.org/faq/what-should-a-meeting-agenda-contain/
