### ISSUE TITLE
FAQ: Meeting Minutes

### ISSUE THREAD

**Issue by ansukert** [itc-wgtools/cPP-Tools#92]
There is no “one size fits all” for meeting minutes. Meeting minutes can be very detailed “point-by-point” explanations of what was discussed at the meeting or meeting minutes can just brief outlines or bullets of what was discussed at the meeting.

The format of meeting minutes can also vary widely. There is no one right format for meeting minutes because the format often depends of what is being discussed at the meeting. For example, some meeting results can best be described in written text, while other meeting results can best be described in tables or graphical format, or a combination of both may be required. So, you have to be flexible in how you do your meeting minutes. You should use whatever word processing tool you are familiar and comfortable with to generate the meeting minutes.

Some general guidelines that you should follow in preparing meeting minutes are:
1.	Always make sure you include in the minutes all the meeting attendees and their affiliation. If you are not sure of all the attendees and their affiliations ask the meeting leader – he/she should know who attended the meeting or should be able to find that out for you.
2.	Make sure you include in the minutes the date, start and stop time of the meeting.
3.	Make sure the minutes indicate what the original meeting agenda topics were and indicate any additions or subtractions from the original agenda. Most often the best way to organize meeting minutes is by agenda topic; that way the reader of the minutes can see what occurred during the discussions for each agenda topic and what the results of those discussions were. 
4.	Make sure you include in the minutes the key points (i.e., opinions, arguments, ideas, conclusions, etc.) covered in the meeting. 
There are no set rules for how much additional information you should include in meeting minutes. My rule-of-thumb is to include the detail I feel readers of the minutes need to understand the discussions at the meeting, but no more than that. What that “no more” line is subjective, but from experience you get a feel for where that line is.
Others may take what I call the “Dragnet” approach – just the main points and no more. Or it can be somewhere in between. The point is that it is essentially up to the person doing the minutes to decide how much detail to include in the minutes.
5.	Include any action items with the responsible person for that action item. One thing many of us don’t do in minutes that we should do is assign a due date for the action items; you should do that for all action items assigned. 
6.	If the meeting is one of a recurring set of meetings, it is a good idea at the end of the minutes to indicate when the next meeting of that set of meetings will occur.

When you are done with the meeting minutes and have done the necessary review and spell-checking, you should generate a PDF version of the meeting minutes; that should be the version you should send out and store. 

As far as sending out the meeting minutes, it is easier if you have a pre-defined DL to send the meeting minutes to, especially if there are a large number of members in the iTC. Otherwise, keep a list of email addresses you need to send the minutes to. Usually, the actual minutes are an attachment to the email announcing the minutes; the email itself should just state something like “Attached are the minutes from the ABC iTC meeting held on <Date>”. It’s a good idea in the email announcing the minutes, if applicable, to provide a link to where the minutes are stored.   

Meeting minutes should be stored in a repository of some type that is accessible to all the members of the iTC. Most iTCs are using OnlyOffice, with each iTC setting up its own project set up on OnlyOffice. However, the iTC can choose to use whatever available repository they want to use such as GitHub to store the minutes. The key is that whatever repository is used it has to be available to all the members of the iTC. 

Whatever repository is used, there should be a ‘Meeting Minutes’ folder or collection set up. It is up to the iTC whether they create a separate subfolder under the main ‘Meeting Minutes’ folder for each meeting or just store all the minutes under the main ‘Meeting Minutes’ folder; either way is acceptable. The repository chosen should also have authentication capability to permit individuals outside the iTC to access the folder or collection containing the minutes.

Finally, it is good practice to make sure the meeting minutes are sent out as soon as possible after the meeting is completed and are stored in the ‘meeting minutes’ repository before they are sent out.

**Comment by woodbe** [comment]
https://www.ccusersforum.org/faq/what-should-meeting-minutes-contain/
