### ISSUE TITLE
FAQ: Lessons Learned

### ISSUE THREAD

**Issue by mmbarry** [itc-wgtools/cPP-Tools#93]
What are some lessons learned from completed iTC work?

- It is preferable to have some sort of draft document to start with to kick off the creation of document.  Use an older PP from the same technology or even another cPP just to have something to start with to get the ideas flowing. 
- Keep the first document iteration simple at first and save major updates for subsequent revisions.
- If you cannot easily draft an evaluation activity, then it is likely a sign that the SFR should not be included.
- Allow for brainstorming to get more ideas out for open discussions.  Some meetings may end up being discussion only and that is okay.
- Assign specific technical editor to be ultimately responsible for cPP and SD documents.
- You will find some pieces of work are better done offline or in smaller groups.  Small sub-groups of 2-3 people work best for large editing jobs.  Substantive changes can be reviewed with the larger group afterwards.  Formatting, grammar, style changes do not need this larger review.
- Consider alternating calls to accommodate different time zones and technical content discussions.  
- Ensure you have at least 3-4 people who have the time and ability to put in the work.
- Try to have an in-person working session early on in the cPP development.  
- Chair is a facilitator…you don’t have to have all the answers.
- Scheme sponsor involvement is important to keep work progressing.  Outstanding questions can be more quickly answered to minimize delay to any work effort.  It also ensures more buy-in during final publication
- Have patience!

**Comment by woodbe** [comment]
https://www.ccusersforum.org/faq/what-are-some-lessons-learned-from-completed-itc-work/
