### ISSUE TITLE
FAQ: Voting

### ISSUE THREAD

**Issue by ansukert** [itc-wgtools/cPP-Tools#98]
Decision making is a critical process in any iTC. Technical and editorial issues will come up as the iTC works to create the cPP, SD and all of the other documentation that an iTC has to produce. Making these technical and editorial decisions is sometimes difficult for a myriad of reasons – issue complexity, existence of multiple solutions, necessity to meet multiple Common Criteria Schemes with differing viewpoints, etc.

The goal is always to make decisions via achieving consensus - consensus is the default and strongly preferred method for issue resolution - but sometimes that is not possible. In cases where consensus cannot be achieved then the iTC needs to implement some type of voting process to resolve issue. 

Some typical questions regarding iTC voting are:
1.	**How long should you try to achieve consensus before going to the voting process?** 
The standard rule of thumb is one month, but the iTC Chair/Deputy Chair should use some common sense – when it becomes clear consensus is not going to be reached even if it is only after two weeks, go to the voting process.

2.	**Who should be able to vote in the iTC?** 
This is somewhat dependent on the size of the iTC. For iTCs with a small number of members generally every iTC member can have one vote. However, for iTCs with a large number of members what is typically done is that one vote is allowed for each member organization, not for each individual member.  “Organization” is defined according to the definition adopted by the CC Users Forum; for commercial enterprises, a parent company and all of its divisions and subsidiaries constitute one organization. For organizations that have multiple members in the iTC, it’s up to the organization to determine who/how that organization will cast its vote.

3.	**What is a typical voting process?** 
A typical voting process is defined below:
a.	A Call for Votes is posted, including the mechanism for casting ballots and time period during which ballots are accepted
b.	At the end of the voting period, ballots are tabulated and reviewed by the Chair or the Technical Editor
c.	Results of voting are posted, including a summary of the vote and the votes cast by each organization. 
This process is illustrated below. A typical voting cycle should be completed within a three-week period. Some voting periods may be longer due to holidays or other events. 
 
![image](https://user-images.githubusercontent.com/50451958/105876703-378f3a80-5fcd-11eb-8b28-c1bf970c835c.png)

Figure 1 Guideline Voting Process
The three-week voting period is typical as stated above, but an iTC can choose to do it quicker if necessary.  

4.	**What type of voting scheme should be used?** 
There are many different voting schemes an iTC could use, but the simpler the voting scheme the better. Most iTCs use the following scheme:
Votes submitted shall be explicit: positive (or Yes), negative (or No), or abstention. A positive vote may be accompanied by editorial or technical comments; a negative vote has to be accompanied by the technical reason(s) for the negative vote. A member may not cast an affirmative vote that is conditional on the acceptance of modifications.
This means that the proposal being put for a decision or vote has to be in a form such that a voter can vote ‘Yes’ or ‘No’ to it. 
The iTC is free to come up with its own voting scheme, but it has to be one that will result is a decision according to the ToR

BEW: Add a link to question 6 when posting this

5.	**Does there need to be a quorum for the vote to be valid?** 
That is up to the iTC whether to set quorum requirements for a vote to be valid. If the iTC does want a quorum of responders for a vote to be valid, typically quorum requirements are set at either 25% or 50% of eligible organizations/members.

BEW: We should think about quorum, and where it applies. I would normally think this is only for votes taken on a call, but there could be a requirement for a minimum number of entities to cast a ballot to be considered valid.

6.	**Should approval be based on a simple majority or a ‘’super majority” or some other criteria?**
Typically, approval is set at a 2/3 majority of the votes in favor of whatever is being voted on with the following caveats:
•	No more than 25% of the votes can be negative votes’
•	Negative votes without accompanying technical reasons and abstentions do not count towards the total
An iTC is free to only require a simple majority to approve a vote or not require either of these caveats or 

BEW: Note that this is the default voting scheme in the ToR template

7.	**Where is all of the rules around the voting process documented?** 
All of the details around the voting process are documented in the Terms of Reference (ToR) document that is one of the required documents the iTC has to produce per the CCDB cPP Development Process.

**Comment by woodbe** [comment]
Consider adding IT-specific voting expectations/questions

**Comment by woodbe** [comment]
Create a new FAQ category specifically for voting and place these as individual questions there

**Comment by woodbe** [comment]
Quorum does not seem like a problem now, so not bring it up at this point.

**Comment by woodbe** [comment]
https://www.ccusersforum.org/faq/general-decision-making/
https://www.ccusersforum.org/faq/how-long-should-you-try-to-achieve-consensus-before-going-to-the-voting-process/
https://www.ccusersforum.org/faq/who-should-be-able-to-vote-in-the-itc/
https://www.ccusersforum.org/faq/what-is-a-typical-voting-process/
https://www.ccusersforum.org/faq/what-type-of-voting-scheme-should-be-used/
https://www.ccusersforum.org/faq/does-there-need-to-be-a-quorum-for-the-vote-to-be-valid/
https://www.ccusersforum.org/faq/should-approval-be-based-on-a-simple-majority-or-a-super-majority-or-some-other-criteria/
https://www.ccusersforum.org/faq/where-is-all-of-the-rules-around-the-voting-process-documented/
