### ISSUE TITLE
FAQ: Scheme Membership in the Interpretation Team

### ISSUE THREAD

**Issue by Kneckter** [itc-wgtools/cPP-Tools#99]
Q: With multiple cPPs being developed within the CCRA nations, how should a Scheme participate in the various Interpretation Teams (ITs) that interpretate those cPPs?

A: Membership in an IT for a cPP is general limited to a certain number of representatives. Each iTC may have different rules on how new applicants can join the IT but there should be only one representative per organization (e.g., company or Scheme) in the IT. This allows Schemes to participate in the interpretate of cPPs but does not require a representative to be part of the IT. Note that only members of the iTC should become IT members as participating in the cPP's active community gives them more experience with how the cPP is used. 

Schemes that do not have a representative in the IT can still interact with the IT. A Scheme can forward any interpretations their evaluations need to the IT and discuss the outcomes with the ITs before providing them to the evaluation teams.

**Comment by woodbe** [comment]
add link to IT membership doc
reference that some ITs may not have voting for scheme participants (but others might)

**Comment by woodbe** [comment]
Here is what I have as a draft:


<p>Membership in an IT for a cPP is general limited to a certain number of representatives. Each iTC may have different rules on how new applicants can join the IT but there should be only one representative per organization (e.g., company or Scheme) in the IT. This allows Schemes to participate in the interpret of cPPs but does not require a representative to be part of the IT. Note that only members of the iTC should become IT members as actively participating in the community gives them more experience with how the cPP is used.</p>



<p>Schemes that do not have a representative in the IT can still interact with the IT. A Scheme can forward any interpretations their evaluations need to the IT and discuss the outcomes with the ITs before providing them to the evaluation teams.</p>



<p>A general template for IT membership can be found <a rel="noreferrer noopener" href="https://github.com/itc-wgtools/iTC-docs/blob/master/IT_membership.adoc" data-type="URL" data-id="https://github.com/itc-wgtools/iTC-docs/blob/master/IT_membership.adoc" target="_blank">here</a>. This template provides for non-voting membership, allowing for inclusion in an IT without needing to provide voting rights. Non-voting membership can provide a way to encourage Scheme participation without potentially creating conflicts between the iTC and the Scheme about whether to accept interpretations that are approved by the IT.</p>

**Comment by woodbe** [comment]
this is good to go

**Comment by woodbe** [comment]
https://www.ccusersforum.org/faq/scheme-it-participation/
